// Code generated by protoc-gen-go.
// source: config.proto
// DO NOT EDIT!

/*
Package config is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	Config
	BlockSigner
	OptionString
	OptionSet
*/
package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import bc "chain/protocol/bc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	IsSigner             bool           `protobuf:"varint,2,opt,name=is_signer,json=isSigner" json:"is_signer,omitempty"`
	IsGenerator          bool           `protobuf:"varint,3,opt,name=is_generator,json=isGenerator" json:"is_generator,omitempty"`
	BlockchainId         *bc.Hash       `protobuf:"bytes,4,opt,name=blockchain_id,json=blockchainId" json:"blockchain_id,omitempty"`
	GeneratorUrl         string         `protobuf:"bytes,5,opt,name=generator_url,json=generatorUrl" json:"generator_url,omitempty"`
	GeneratorAccessToken string         `protobuf:"bytes,6,opt,name=generator_access_token,json=generatorAccessToken" json:"generator_access_token,omitempty"`
	BlockHsmUrl          string         `protobuf:"bytes,7,opt,name=block_hsm_url,json=blockHsmUrl" json:"block_hsm_url,omitempty"`
	BlockHsmAccessToken  string         `protobuf:"bytes,8,opt,name=block_hsm_access_token,json=blockHsmAccessToken" json:"block_hsm_access_token,omitempty"`
	ConfiguredAt         uint64         `protobuf:"varint,9,opt,name=configured_at,json=configuredAt" json:"configured_at,omitempty"`
	BlockPub             []byte         `protobuf:"bytes,10,opt,name=block_pub,json=blockPub,proto3" json:"block_pub,omitempty"`
	Signers              []*BlockSigner `protobuf:"bytes,11,rep,name=signers" json:"signers,omitempty"`
	Quorum               uint32         `protobuf:"varint,12,opt,name=quorum" json:"quorum,omitempty"`
	MaxIssuanceWindowMs  uint64         `protobuf:"varint,13,opt,name=max_issuance_window_ms,json=maxIssuanceWindowMs" json:"max_issuance_window_ms,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Config) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Config) GetIsSigner() bool {
	if m != nil {
		return m.IsSigner
	}
	return false
}

func (m *Config) GetIsGenerator() bool {
	if m != nil {
		return m.IsGenerator
	}
	return false
}

func (m *Config) GetBlockchainId() *bc.Hash {
	if m != nil {
		return m.BlockchainId
	}
	return nil
}

func (m *Config) GetGeneratorUrl() string {
	if m != nil {
		return m.GeneratorUrl
	}
	return ""
}

func (m *Config) GetGeneratorAccessToken() string {
	if m != nil {
		return m.GeneratorAccessToken
	}
	return ""
}

func (m *Config) GetBlockHsmUrl() string {
	if m != nil {
		return m.BlockHsmUrl
	}
	return ""
}

func (m *Config) GetBlockHsmAccessToken() string {
	if m != nil {
		return m.BlockHsmAccessToken
	}
	return ""
}

func (m *Config) GetConfiguredAt() uint64 {
	if m != nil {
		return m.ConfiguredAt
	}
	return 0
}

func (m *Config) GetBlockPub() []byte {
	if m != nil {
		return m.BlockPub
	}
	return nil
}

func (m *Config) GetSigners() []*BlockSigner {
	if m != nil {
		return m.Signers
	}
	return nil
}

func (m *Config) GetQuorum() uint32 {
	if m != nil {
		return m.Quorum
	}
	return 0
}

func (m *Config) GetMaxIssuanceWindowMs() uint64 {
	if m != nil {
		return m.MaxIssuanceWindowMs
	}
	return 0
}

type BlockSigner struct {
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Pubkey      []byte `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Url         string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
}

func (m *BlockSigner) Reset()                    { *m = BlockSigner{} }
func (m *BlockSigner) String() string            { return proto.CompactTextString(m) }
func (*BlockSigner) ProtoMessage()               {}
func (*BlockSigner) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlockSigner) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *BlockSigner) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *BlockSigner) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type OptionString struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *OptionString) Reset()                    { *m = OptionString{} }
func (m *OptionString) String() string            { return proto.CompactTextString(m) }
func (*OptionString) ProtoMessage()               {}
func (*OptionString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OptionString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type OptionSet struct {
	Values [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (m *OptionSet) Reset()                    { *m = OptionSet{} }
func (m *OptionSet) String() string            { return proto.CompactTextString(m) }
func (*OptionSet) ProtoMessage()               {}
func (*OptionSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OptionSet) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "config.Config")
	proto.RegisterType((*BlockSigner)(nil), "config.BlockSigner")
	proto.RegisterType((*OptionString)(nil), "config.OptionString")
	proto.RegisterType((*OptionSet)(nil), "config.OptionSet")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x4f, 0x6f, 0xd4, 0x30,
	0x10, 0xc5, 0x95, 0x4d, 0x9b, 0x66, 0x27, 0x09, 0x42, 0xde, 0x6a, 0x65, 0x95, 0x4b, 0xc8, 0x72,
	0xc8, 0xa5, 0xbb, 0x52, 0xcb, 0x17, 0x28, 0x1c, 0x68, 0x0f, 0x08, 0x94, 0x82, 0x90, 0xb8, 0x58,
	0x8e, 0x63, 0x76, 0xad, 0x4d, 0xe2, 0x25, 0x4e, 0x68, 0xf9, 0xe8, 0xdc, 0x90, 0xc7, 0xd9, 0x3f,
	0xbd, 0x65, 0xde, 0xfb, 0xe5, 0x79, 0x3c, 0x1e, 0x88, 0x85, 0x6e, 0x7f, 0xa9, 0xf5, 0x72, 0xd7,
	0xe9, 0x5e, 0x93, 0xc0, 0x55, 0x57, 0x57, 0x62, 0xc3, 0x55, 0xbb, 0x42, 0x51, 0xe8, 0x7a, 0x55,
	0x8a, 0x55, 0x29, 0x1c, 0x93, 0xfd, 0xf3, 0x21, 0xf8, 0x88, 0x18, 0x79, 0x05, 0x13, 0x55, 0x51,
	0x2f, 0xf5, 0xf2, 0x69, 0x31, 0x51, 0x15, 0x79, 0x03, 0x53, 0x65, 0x98, 0x51, 0xeb, 0x56, 0x76,
	0x74, 0x92, 0x7a, 0x79, 0x58, 0x84, 0xca, 0x3c, 0x62, 0x4d, 0xde, 0x42, 0xac, 0x0c, 0x5b, 0xcb,
	0x56, 0x76, 0xbc, 0xd7, 0x1d, 0xf5, 0xd1, 0x8f, 0x94, 0xf9, 0xb4, 0x97, 0xc8, 0x35, 0x24, 0x65,
	0xad, 0xc5, 0x16, 0x4f, 0x67, 0xaa, 0xa2, 0x67, 0xa9, 0x97, 0x47, 0x37, 0xe1, 0xb2, 0x14, 0xcb,
	0x7b, 0x6e, 0x36, 0x45, 0x7c, 0xb4, 0x1f, 0x2a, 0xb2, 0x80, 0xe4, 0x10, 0xc7, 0x86, 0xae, 0xa6,
	0xe7, 0xd8, 0x49, 0x7c, 0x10, 0xbf, 0x77, 0x35, 0x79, 0x0f, 0xf3, 0x23, 0xc4, 0x85, 0x90, 0xc6,
	0xb0, 0x5e, 0x6f, 0x65, 0x4b, 0x03, 0xa4, 0x2f, 0x0f, 0xee, 0x1d, 0x9a, 0xdf, 0xac, 0x47, 0xb2,
	0xb1, 0x13, 0xb6, 0x31, 0x0d, 0x46, 0x5f, 0x20, 0x1c, 0xa1, 0x78, 0x6f, 0x1a, 0x9b, 0x7c, 0x0b,
	0xf3, 0x23, 0xf3, 0x22, 0x39, 0x44, 0x78, 0xb6, 0x87, 0x4f, 0x83, 0x17, 0x90, 0xb8, 0x19, 0x0f,
	0x9d, 0xac, 0x18, 0xef, 0xe9, 0x34, 0xf5, 0xf2, 0xb3, 0x22, 0x3e, 0x8a, 0x77, 0xbd, 0x9d, 0xa3,
	0x4b, 0xde, 0x0d, 0x25, 0x85, 0xd4, 0xcb, 0xe3, 0x22, 0x44, 0xe1, 0xeb, 0x50, 0x92, 0x6b, 0xb8,
	0x70, 0x13, 0x36, 0x34, 0x4a, 0xfd, 0x3c, 0xba, 0x99, 0x2d, 0xc7, 0x37, 0xfc, 0x60, 0x11, 0x37,
	0xed, 0x62, 0xcf, 0x90, 0x39, 0x04, 0xbf, 0x07, 0xdd, 0x0d, 0x0d, 0x8d, 0x53, 0x2f, 0x4f, 0x8a,
	0xb1, 0xb2, 0xdd, 0x37, 0xfc, 0x99, 0x29, 0x63, 0x06, 0xde, 0x0a, 0xc9, 0x9e, 0x54, 0x5b, 0xe9,
	0x27, 0xd6, 0x18, 0x9a, 0x60, 0x47, 0xb3, 0x86, 0x3f, 0x3f, 0x8c, 0xe6, 0x0f, 0xf4, 0x3e, 0x9b,
	0xec, 0x27, 0x44, 0x27, 0x87, 0xd8, 0x27, 0x7d, 0x71, 0x6f, 0xb7, 0x09, 0x11, 0x3f, 0xb9, 0xef,
	0x1c, 0x82, 0xdd, 0x50, 0x6e, 0xe5, 0x5f, 0xdc, 0x87, 0xb8, 0x18, 0x2b, 0xf2, 0x1a, 0x7c, 0x3b,
	0x56, 0x1f, 0xff, 0xb0, 0x9f, 0xd9, 0x3b, 0x88, 0xbf, 0xec, 0x7a, 0xa5, 0xdb, 0xc7, 0xbe, 0x53,
	0xed, 0x9a, 0x5c, 0xc2, 0xf9, 0x1f, 0x5e, 0x0f, 0x72, 0x4c, 0x75, 0x45, 0xb6, 0x80, 0xe9, 0x48,
	0xc9, 0xde, 0x86, 0xa3, 0x6a, 0xa8, 0x97, 0xfa, 0x36, 0xdc, 0x55, 0x65, 0x80, 0x9b, 0x7a, 0xfb,
	0x3f, 0x00, 0x00, 0xff, 0xff, 0xca, 0xa6, 0xd5, 0x97, 0xdd, 0x02, 0x00, 0x00,
}
