// Code generated by protoc-gen-go.
// source: remotehsm.proto
// DO NOT EDIT!

/*
Package blocksigner is a generated protocol buffer package.

It is generated from these files:
	remotehsm.proto

It has these top-level messages:
	RemoteHSM
*/
package blocksigner

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RemoteHSM struct {
	Url         string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
}

func (m *RemoteHSM) Reset()                    { *m = RemoteHSM{} }
func (m *RemoteHSM) String() string            { return proto.CompactTextString(m) }
func (*RemoteHSM) ProtoMessage()               {}
func (*RemoteHSM) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RemoteHSM) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RemoteHSM) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func init() {
	proto.RegisterType((*RemoteHSM)(nil), "blocksigner.RemoteHSM")
}

func init() { proto.RegisterFile("remotehsm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4a, 0xcd, 0xcd,
	0x2f, 0x49, 0xcd, 0x28, 0xce, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0xca, 0xc9,
	0x4f, 0xce, 0x2e, 0xce, 0x4c, 0xcf, 0x4b, 0x2d, 0x52, 0x72, 0xe0, 0xe2, 0x0c, 0x02, 0xcb, 0x7b,
	0x04, 0xfb, 0x0a, 0x09, 0x70, 0x31, 0x97, 0x16, 0xe5, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x81, 0x98, 0x42, 0x8a, 0x5c, 0x3c, 0x89, 0xc9, 0xc9, 0xa9, 0xc5, 0xc5, 0xf1, 0x25, 0xf9, 0xd9,
	0xa9, 0x79, 0x12, 0x4c, 0x60, 0x29, 0x6e, 0x88, 0x58, 0x08, 0x48, 0x28, 0x89, 0x0d, 0x6c, 0xaa,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xbd, 0xb3, 0x91, 0x68, 0x00, 0x00, 0x00,
}
